name: farts
description: Flutter charts
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
